apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-todo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-todo
  template:
    metadata:
      labels:
        app: node-todo
    spec:
      containers:
      - name: node-todo-container
        image: vinod200103/nodejs-project:1.3 # Replace with your Docker image
        ports:
        - containerPort: 5000  # Assuming your React app listens on port 80