
apiVersion: v1
kind: Service
metadata:
  name: node-todo-service
spec:
  selector:
    app: node-todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
